//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.6.
// ttlitex.rc

#define IDC_LITEX_KERNEL                    1002
#define IDC_LITEX_BOOT_ADDR                 1003
#define IDC_LITEX_CHOOSE_KERNEL_BUTTON      1004
#define IDC_LITEX_ACTIVE                    1005

#define IDD_SETUP_LITEX                     1001

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1006
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
