name: CI
on:
  push:
    branches:
      - '**'
    tags:
      - v*
  pull_request:
permissions:
  contents: write

jobs:
  build:
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win32
    - name: Install 32-bit Rust Compiler
      run: just prereq-32-msvc
    # https://github.com/ilammy/msvc-dev-cmd?tab=readme-ov-file#name-conflicts-with-shell-bash
    - name: Remove GNU link
      run: sh -c 'rm /usr/bin/link'
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.7
    - name: Build DLL
      run: just build-32-msvc
    # No cargo wix action, and the markdown-extract action is Linux-only :(...
    - name: Inject sccache Vars
      run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
    - name: Create MSI
      if: runner.os == 'Windows'
      run: |
          cargo install cargo-wix
          just wix-msi-32-msvc "-${{github.ref_name}}"
    - name: Install ZIP
      if: ${{ runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v') }}
      run: choco install zip
    - name: Make ZIP file
      if: ${{ runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v') }}
      run: just prepare-release-zip "-${{github.ref_name}}"
    - name: Extract Release Notes From CHANGELOG.md
      if: ${{ runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v') }}
      run: |
          cargo install markdown-extract-cli
          markdown-extract [${{github.ref_name}}] CHANGELOG.md > CHANGELOG-extracted.md
    - name: Release
      uses: softprops/action-gh-release@v2
      if: ${{ runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v') }}
      with:
          body_path: CHANGELOG-extracted.md
          files: |
            target/i686-pc-windows-msvc/wix/*.msi
            tt-litex-${{github.ref_name}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

