name: Test Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: extractions/setup-just@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win32
    - name: Install 32-bit Rust Compiler
      run: just prereq-32-msvc
    # https://github.com/ilammy/msvc-dev-cmd?tab=readme-ov-file#name-conflicts-with-shell-bash
    - name: Remove GNU link
      run: sh -c 'rm /usr/bin/link'
    - name: Build DLL
      run: just build-32-msvc
